config/routes.rb
Rails.application.routes.draw do
  resources :simple_widgets
  root to: "simple_widgets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/simple_widget.rb
class SimpleWidget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_widgets_controller.rb
class SimpleWidgetsController < ApplicationController
  before_action :set_simple_widget, only: [:show, :edit, :update, :destroy]

  # GET /simple_widgets
  # GET /simple_widgets.json
  def index
    @simple_widgets = SimpleWidget.all
  end

  # GET /simple_widgets/1
  # GET /simple_widgets/1.json
  def show
  end

  # GET /simple_widgets/new
  def new
    raise "Oh noes! Something be broke!"
    @simple_widget = SimpleWidget.new
  end

  # GET /simple_widgets/1/edit
  def edit
  end

  # POST /simple_widgets
  # POST /simple_widgets.json
  def create
    @simple_widget = SimpleWidget.new(simple_widget_params)

    respond_to do |format|
      if @simple_widget.save
        format.html { redirect_to @simple_widget, notice: 'Simple widget was successfully created.' }
        format.json { render :show, status: :created, location: @simple_widget }
      else
        format.html { render :new }
        format.json { render json: @simple_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simple_widgets/1
  # PATCH/PUT /simple_widgets/1.json
  def update
    respond_to do |format|
      if @simple_widget.update(simple_widget_params)
        format.html { redirect_to @simple_widget, notice: 'Simple widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @simple_widget }
      else
        format.html { render :edit }
        format.json { render json: @simple_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simple_widgets/1
  # DELETE /simple_widgets/1.json
  def destroy
    @simple_widget.destroy
    respond_to do |format|
      format.html { redirect_to simple_widgets_url, notice: 'Simple widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simple_widget
      @simple_widget = SimpleWidget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simple_widget_params
      params.require(:simple_widget).permit(:name, :count, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_widgets_helper.rb
module SimpleWidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_widgets/_form.html.erb
<%= form_with(model: simple_widget, local: true) do |form| %>
  <% if simple_widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(simple_widget.errors.count, "error") %> prohibited this simple_widget from being saved:</h2>

      <ul>
      <% simple_widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.text_field :count %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/simple_widgets/edit.html.erb
<h1>Editing Simple Widget</h1>

<%= render 'form', simple_widget: @simple_widget %>

<%= link_to 'Show', @simple_widget %> |
<%= link_to 'Back', simple_widgets_path %>

app/views/simple_widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Simple Widgets</h1>
<p>They are simple.</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simple_widgets.each do |simple_widget| %>
      <tr>
        <td><%= simple_widget.name %></td>
        <td><%= simple_widget.count %></td>
        <td><%= simple_widget.comments %></td>
        <td><%= link_to 'Show', simple_widget %></td>
        <td><%= link_to 'Edit', edit_simple_widget_path(simple_widget) %></td>
        <td><%= link_to 'Destroy', simple_widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simple Widget', new_simple_widget_path %>

app/views/simple_widgets/new.html.erb
<h1>New Simple Widget</h1>
<p>Make a new widget!!</p>

<%= render 'form', simple_widget: @simple_widget %>

<%= link_to 'Back', simple_widgets_path %>

app/views/simple_widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @simple_widget.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @simple_widget.count %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @simple_widget.comments %>
</p>

<%= link_to 'Edit', edit_simple_widget_path(@simple_widget) %> |
<%= link_to 'Back', simple_widgets_path %>